[package]
name = "recipe-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
scraper = "0.19"
urlencoding = "2.1"
rusqlite = { version = "0.29", features = ["bundled"] }
dialoguer = "0.10"
colored = "2.0"
